"""empty message

Revision ID: 8ae2d0d16ad8
Revises: 
Create Date: 2026-07-19 16:57:13.620839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ae2d0d16ad8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('courses')
    op.drop_table('worker_skills')
    op.drop_table('grades')
    op.drop_index(op.f('ships_model_idx'), table_name='ships')
    op.drop_table('ships')
    op.drop_table('sectors')
    op.drop_table('qualifications')
    op.drop_table('space_stations')
    op.drop_table('couriers')
    op.drop_table('planets')
    op.drop_table('workers_core')
    op.drop_table('courier_qualifications')
    op.drop_table('students')
    op.drop_table('skills_orm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_orm',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_orm_pkey'))
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('register', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_table('courier_qualifications',
    sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qualification_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('workers_core',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_core_pkey'))
    )
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('planet_pkey'))
    )
    op.create_table('couriers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('courier_pkey'))
    )
    op.create_table('space_stations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('combat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('energy_output', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('space_stations_pkey'))
    )
    op.create_table('qualifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('qualifications_pkey'))
    )
    op.create_table('sectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('danger_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('danger_level >= 0 AND danger_level <= 5', name=op.f('sectors_danger_level_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('sectors_pkey')),
    sa.UniqueConstraint('sector_code', name=op.f('sectors_sector_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('courier_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('ship_pkey'))
    )
    op.create_index(op.f('ships_model_idx'), 'ships', ['model'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cours_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('not_started', 'in_progerss', 'completed', 'failed', name='status'), autoincrement=False, nullable=False),
    sa.Column('assessment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('assessment >= 0 AND assessment <= 100', name=op.f('grades_assessment_check')),
    sa.ForeignKeyConstraint(['cours_id'], ['courses.id'], name=op.f('grades_cours_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('grades_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('grades_pkey'))
    )
    op.create_table('worker_skills',
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills_orm.id'], name=op.f('worker_skills_skill_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers_orm.id'], name=op.f('worker_skills_worker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'skill_id', name=op.f('worker_skills_pkey'))
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey'))
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('order_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], name=op.f('ship_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###
