employees_db = [
    {
        "employee_id": 1001,
        "first_name": "John",
        "last_name": "Smith",
        "department": "IT",
        "role": "Backend",
        "salary": 4200.0,
        "internal_token": "emp_1001_a7x91",
        "skills": ["Python", "FastAPI", "PostgreSQL"],
    },
    {
        "employee_id": 1002,
        "first_name": "Emma",
        "last_name": "Johnson",
        "department": "HR",
        "role": "HR Manager",
        "salary": 3500.0,
        "internal_token": "emp_1002_k2m84",
        "skills": ["Recruitment", "Communication"],
    },
    {
        "employee_id": 1003,
        "first_name": "Michael",
        "last_name": "Brown",
        "department": "Finance",
        "role": "Accountant",
        "salary": 3900.0,
        "internal_token": "emp_1003_t9q21",
        "skills": ["Excel", "Accounting"],
    },
    {
        "employee_id": 1004,
        "first_name": "Sophia",
        "last_name": "Davis",
        "department": "Marketing",
        "role": "Marketing Specialist",
        "salary": 3700.0,
        "internal_token": "emp_1004_n8f72",
        "skills": ["SEO", "Content"],
    },
    {
        "employee_id": 1005,
        "first_name": "Daniel",
        "last_name": "Wilson",
        "department": "IT",
        "role": "Frontend",
        "salary": 4100.0,
        "internal_token": "emp_1005_r5v33",
        "skills": ["JavaScript", "React", "CSS"],
    },
    {
        "employee_id": 1006,
        "first_name": "Olivia",
        "last_name": "Taylor",
        "department": "IT",
        "role": "DevOps",
        "salary": 5000.0,
        "internal_token": "emp_1006_j4k18",
        "skills": ["Docker", "Kubernetes", "Linux"],
    },
    {
        "employee_id": 1007,
        "first_name": "James",
        "last_name": "Anderson",
        "department": "Finance",
        "role": "Financial Analyst",
        "salary": 4300.0,
        "internal_token": "emp_1007_h9c41",
        "skills": ["Power BI", "Excel"],
    },
    {
        "employee_id": 1008,
        "first_name": "Ava",
        "last_name": "Thomas",
        "department": "Marketing",
        "role": "SMM Manager",
        "salary": 3400.0,
        "internal_token": "emp_1008_z3x52",
        "skills": ["Instagram", "TikTok", "Analytics"],
    },
    {
        "employee_id": 1009,
        "first_name": "William",
        "last_name": "Moore",
        "department": "IT",
        "role": "Backend",
        "salary": 4700.0,
        "internal_token": "emp_1009_q8w14",
        "skills": ["Python", "Redis", "FastAPI"],
    },
    {
        "employee_id": 1010,
        "first_name": "Mia",
        "last_name": "Martin",
        "department": "HR",
        "role": "Recruiter",
        "salary": 3300.0,
        "internal_token": "emp_1010_l5g82",
        "skills": ["Interviews", "LinkedIn"],
    },
    {
        "employee_id": 1011,
        "first_name": "Benjamin",
        "last_name": "Lee",
        "department": "IT",
        "role": "Backend",
        "salary": 5200.0,
        "internal_token": "emp_1011_b6n91",
        "skills": ["Python", "Django", "PostgreSQL"],
    },
    {
        "employee_id": 1012,
        "first_name": "Charlotte",
        "last_name": "Perez",
        "department": "Marketing",
        "role": "Designer",
        "salary": 3600.0,
        "internal_token": "emp_1012_f2r37",
        "skills": ["Figma", "Photoshop"],
    },
    {
        "employee_id": 1013,
        "first_name": "Lucas",
        "last_name": "White",
        "department": "IT",
        "role": "DevOps",
        "salary": 5400.0,
        "internal_token": "emp_1013_m4p88",
        "skills": ["AWS", "Terraform", "Docker"],
    },
    {
        "employee_id": 1014,
        "first_name": "Amelia",
        "last_name": "Harris",
        "department": "Finance",
        "role": "Auditor",
        "salary": 4100.0,
        "internal_token": "emp_1014_c8d55",
        "skills": ["Audit", "Excel"],
    },
    {
        "employee_id": 1015,
        "first_name": "Henry",
        "last_name": "Clark",
        "department": "IT",
        "role": "Frontend",
        "salary": 4300.0,
        "internal_token": "emp_1015_t2w67",
        "skills": ["Vue", "TypeScript"],
    },
    {
        "employee_id": 1016,
        "first_name": "Evelyn",
        "last_name": "Lewis",
        "department": "HR",
        "role": "HR Specialist",
        "salary": 3400.0,
        "internal_token": "emp_1016_a9r44",
        "skills": ["Onboarding", "People Management"],
    },
    {
        "employee_id": 1017,
        "first_name": "Alexander",
        "last_name": "Walker",
        "department": "Marketing",
        "role": "Copywriter",
        "salary": 3200.0,
        "internal_token": "emp_1017_u7m20",
        "skills": ["Copywriting", "SEO"],
    },
    {
        "employee_id": 1018,
        "first_name": "Harper",
        "last_name": "Hall",
        "department": "IT",
        "role": "Backend",
        "salary": 4900.0,
        "internal_token": "emp_1018_v4e76",
        "skills": ["Python", "SQLAlchemy"],
    },
    {
        "employee_id": 1019,
        "first_name": "Ethan",
        "last_name": "Allen",
        "department": "Finance",
        "role": "Financial Analyst",
        "salary": 4400.0,
        "internal_token": "emp_1019_s8y63",
        "skills": ["Excel", "Forecasting"],
    },
    {
        "employee_id": 1020,
        "first_name": "Abigail",
        "last_name": "Young",
        "department": "Marketing",
        "role": "Content Manager",
        "salary": 3500.0,
        "internal_token": "emp_1020_x5n29",
        "skills": ["Content", "Analytics"],
    },
    {
        "employee_id": 1021,
        "first_name": "David",
        "last_name": "King",
        "department": "IT",
        "role": "DevOps",
        "salary": 5600.0,
        "internal_token": "emp_1021_h3r81",
        "skills": ["CI/CD", "Docker", "Linux"],
    },
    {
        "employee_id": 1022,
        "first_name": "Ella",
        "last_name": "Scott",
        "department": "HR",
        "role": "Recruiter",
        "salary": 3450.0,
        "internal_token": "emp_1022_q2w94",
        "skills": ["Hiring", "Interviews"],
    },
    {
        "employee_id": 1023,
        "first_name": "Joseph",
        "last_name": "Green",
        "department": "IT",
        "role": "Frontend",
        "salary": 4250.0,
        "internal_token": "emp_1023_k7d66",
        "skills": ["React", "Redux"],
    },
    {
        "employee_id": 1024,
        "first_name": "Grace",
        "last_name": "Baker",
        "department": "Finance",
        "role": "Accountant",
        "salary": 3950.0,
        "internal_token": "emp_1024_p8g10",
        "skills": ["Accounting", "Excel"],
    },
    {
        "employee_id": 1025,
        "first_name": "Matthew",
        "last_name": "Nelson",
        "department": "IT",
        "role": "Backend",
        "salary": 5100.0,
        "internal_token": "emp_1025_e6t91",
        "skills": ["Python", "FastAPI", "Redis"],
    },
    {
        "employee_id": 1026,
        "first_name": "Lily",
        "last_name": "Carter",
        "department": "Marketing",
        "role": "Designer",
        "salary": 3650.0,
        "internal_token": "emp_1026_w1z45",
        "skills": ["Illustrator", "Figma"],
    },
    {
        "employee_id": 1027,
        "first_name": "Samuel",
        "last_name": "Mitchell",
        "department": "IT",
        "role": "DevOps",
        "salary": 5500.0,
        "internal_token": "emp_1027_r9a32",
        "skills": ["AWS", "Kubernetes"],
    },
    {
        "employee_id": 1028,
        "first_name": "Chloe",
        "last_name": "Roberts",
        "department": "HR",
        "role": "HR Manager",
        "salary": 4100.0,
        "internal_token": "emp_1028_l8m73",
        "skills": ["Leadership", "Recruitment"],
    },
    {
        "employee_id": 1029,
        "first_name": "Jack",
        "last_name": "Turner",
        "department": "IT",
        "role": "Backend",
        "salary": 5300.0,
        "internal_token": "emp_1029_n5y17",
        "skills": ["FastAPI", "PostgreSQL", "Docker"],
    },
    {
        "employee_id": 1030,
        "first_name": "Sofia",
        "last_name": "Phillips",
        "department": "Marketing",
        "role": "Marketing Specialist",
        "salary": 3800.0,
        "internal_token": "emp_1030_c4f88",
        "skills": ["SEO", "Google Ads"],
    },
]