employees_db = [
    {
        "employee_id": 1,
        "first_name": "John",
        "last_name": "Smith",
        "department": "IT",
        "role": "Backend",
        "salary": 4200.0,
        "internal_token": "emp_0001",
        "skills": ["Python", "FastAPI", "PostgreSQL"],
    },
    {
        "employee_id": 2,
        "first_name": "Emma",
        "last_name": "Johnson",
        "department": "HR",
        "role": "HR Manager",
        "salary": 3500.0,
        "internal_token": "emp_0002",
        "skills": ["Recruitment", "Communication"],
    },
    {
        "employee_id": 3,
        "first_name": "Michael",
        "last_name": "Brown",
        "department": "Finance",
        "role": "Accountant",
        "salary": 3900.0,
        "internal_token": "emp_0003",
        "skills": ["Excel", "Accounting"],
    },
    {
        "employee_id": 4,
        "first_name": "Sophia",
        "last_name": "Davis",
        "department": "Marketing",
        "role": "Marketing Specialist",
        "salary": 3700.0,
        "internal_token": "emp_0004",
        "skills": ["SEO", "Content"],
    },
    {
        "employee_id": 5,
        "first_name": "Daniel",
        "last_name": "Wilson",
        "department": "IT",
        "role": "Frontend",
        "salary": 4100.0,
        "internal_token": "emp_0005",
        "skills": ["JavaScript", "React", "CSS"],
    },
    {
        "employee_id": 6,
        "first_name": "Olivia",
        "last_name": "Taylor",
        "department": "IT",
        "role": "DevOps",
        "salary": 5000.0,
        "internal_token": "emp_0006",
        "skills": ["Docker", "Kubernetes", "Linux"],
    },
    {
        "employee_id": 7,
        "first_name": "James",
        "last_name": "Anderson",
        "department": "Finance",
        "role": "Financial Analyst",
        "salary": 4300.0,
        "internal_token": "emp_0007",
        "skills": ["Power BI", "Excel"],
    },
    {
        "employee_id": 8,
        "first_name": "Ava",
        "last_name": "Thomas",
        "department": "Marketing",
        "role": "SMM Manager",
        "salary": 3400.0,
        "internal_token": "emp_0008",
        "skills": ["Instagram", "TikTok", "Analytics"],
    },
    {
        "employee_id": 9,
        "first_name": "William",
        "last_name": "Moore",
        "department": "IT",
        "role": "Backend",
        "salary": 4700.0,
        "internal_token": "emp_0009",
        "skills": ["Python", "Redis", "FastAPI"],
    },
    {
        "employee_id": 10,
        "first_name": "Mia",
        "last_name": "Martin",
        "department": "HR",
        "role": "Recruiter",
        "salary": 3300.0,
        "internal_token": "emp_0010",
        "skills": ["Interviews", "LinkedIn"],
    },
    {
        "employee_id": 11,
        "first_name": "Benjamin",
        "last_name": "Lee",
        "department": "IT",
        "role": "Backend",
        "salary": 5200.0,
        "internal_token": "emp_0011",
        "skills": ["Python", "Django", "PostgreSQL"],
    },
    {
        "employee_id": 12,
        "first_name": "Charlotte",
        "last_name": "Perez",
        "department": "Marketing",
        "role": "Designer",
        "salary": 3600.0,
        "internal_token": "emp_0012",
        "skills": ["Figma", "Photoshop"],
    },
    {
        "employee_id": 13,
        "first_name": "Lucas",
        "last_name": "White",
        "department": "IT",
        "role": "DevOps",
        "salary": 5400.0,
        "internal_token": "emp_0013",
        "skills": ["AWS", "Terraform", "Docker"],
    },
    {
        "employee_id": 14,
        "first_name": "Amelia",
        "last_name": "Harris",
        "department": "Finance",
        "role": "Auditor",
        "salary": 4100.0,
        "internal_token": "emp_0014",
        "skills": ["Audit", "Excel"],
    },
    {
        "employee_id": 15,
        "first_name": "Henry",
        "last_name": "Clark",
        "department": "IT",
        "role": "Frontend",
        "salary": 4300.0,
        "internal_token": "emp_0015",
        "skills": ["Vue", "TypeScript"],
    },
    {
        "employee_id": 16,
        "first_name": "Evelyn",
        "last_name": "Lewis",
        "department": "HR",
        "role": "HR Specialist",
        "salary": 3400.0,
        "internal_token": "emp_0016",
        "skills": ["Onboarding", "People Management"],
    },
    {
        "employee_id": 17,
        "first_name": "Alexander",
        "last_name": "Walker",
        "department": "Marketing",
        "role": "Copywriter",
        "salary": 3200.0,
        "internal_token": "emp_0017",
        "skills": ["Copywriting", "SEO"],
    },
    {
        "employee_id": 18,
        "first_name": "Harper",
        "last_name": "Hall",
        "department": "IT",
        "role": "Backend",
        "salary": 4900.0,
        "internal_token": "emp_0018",
        "skills": ["Python", "SQLAlchemy"],
    },
    {
        "employee_id": 19,
        "first_name": "Ethan",
        "last_name": "Allen",
        "department": "Finance",
        "role": "Financial Analyst",
        "salary": 4400.0,
        "internal_token": "emp_0019",
        "skills": ["Excel", "Forecasting"],
    },
    {
        "employee_id": 20,
        "first_name": "Abigail",
        "last_name": "Young",
        "department": "Marketing",
        "role": "Content Manager",
        "salary": 3500.0,
        "internal_token": "emp_0020",
        "skills": ["Content", "Analytics"],
    },
    {
        "employee_id": 21,
        "first_name": "David",
        "last_name": "King",
        "department": "IT",
        "role": "DevOps",
        "salary": 5600.0,
        "internal_token": "emp_0021",
        "skills": ["CI/CD", "Docker", "Linux"],
    },
    {
        "employee_id": 22,
        "first_name": "Ella",
        "last_name": "Scott",
        "department": "HR",
        "role": "Recruiter",
        "salary": 3450.0,
        "internal_token": "emp_0022",
        "skills": ["Hiring", "Interviews"],
    },
    {
        "employee_id": 23,
        "first_name": "Joseph",
        "last_name": "Green",
        "department": "IT",
        "role": "Frontend",
        "salary": 4250.0,
        "internal_token": "emp_0023",
        "skills": ["React", "Redux"],
    },
    {
        "employee_id": 24,
        "first_name": "Grace",
        "last_name": "Baker",
        "department": "Finance",
        "role": "Accountant",
        "salary": 3950.0,
        "internal_token": "emp_0024",
        "skills": ["Accounting", "Excel"],
    },
    {
        "employee_id": 25,
        "first_name": "Matthew",
        "last_name": "Nelson",
        "department": "IT",
        "role": "Backend",
        "salary": 5100.0,
        "internal_token": "emp_0025",
        "skills": ["Python", "FastAPI", "Redis"],
    },
    {
        "employee_id": 26,
        "first_name": "Lily",
        "last_name": "Carter",
        "department": "Marketing",
        "role": "Designer",
        "salary": 3650.0,
        "internal_token": "emp_0026",
        "skills": ["Illustrator", "Figma"],
    },
    {
        "employee_id": 27,
        "first_name": "Samuel",
        "last_name": "Mitchell",
        "department": "IT",
        "role": "DevOps",
        "salary": 5500.0,
        "internal_token": "emp_0027",
        "skills": ["AWS", "Kubernetes"],
    },
    {
        "employee_id": 28,
        "first_name": "Chloe",
        "last_name": "Roberts",
        "department": "HR",
        "role": "HR Manager",
        "salary": 4100.0,
        "internal_token": "emp_0028",
        "skills": ["Leadership", "Recruitment"],
    },
    {
        "employee_id": 29,
        "first_name": "Jack",
        "last_name": "Turner",
        "department": "IT",
        "role": "Backend",
        "salary": 5300.0,
        "internal_token": "emp_0029",
        "skills": ["FastAPI", "PostgreSQL", "Docker"],
    },
    {
        "employee_id": 30,
        "first_name": "Sofia",
        "last_name": "Phillips",
        "department": "Marketing",
        "role": "Marketing Specialist",
        "salary": 3800.0,
        "internal_token": "emp_0030",
        "skills": ["SEO", "Google Ads"],
    },
]
